name: Generate Question Paper

on:
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow secara manual dari tab Actions
    inputs:
      subject:
        description: 'Mata Pelajaran'
        required: true
        default: 'Bahasa Indonesia'
      grade:
        description: 'Kelas'
        required: true
        default: '7A'
      exam_title:
        description: 'Judul Ujian'
        required: true
        default: 'Ulangan Puisi'
      teacher_name:
        description: 'Nama Guru'
        required: true
        default: 'Ibu Siti'
      topic_1:
        description: 'Topik Esai 1 (opsional)'
        required: false
        default: 'Unsur Intrinsik Puisi'
      topic_2:
        description: 'Topik Esai 2 (opsional)'
        required: false
        default: 'Gaya Bahasa'
      topic_3:
        description: 'Topik Esai 3 (opsional)'
        required: false
        default: 'Amanat'

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Mengambil kode repositori Anda

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Versi Python yang digunakan

      - name: Install LaTeX (Tex Live)
        # Instalasi TeX Live bisa memakan waktu sekitar 1-2 menit
        # texlive-latex-base: paket dasar LaTeX
        # texlive-fonts-recommended: font-font penting
        # texlive-pictures: untuk paket graphicx (gambar)
        # texlive-luatex: diperlukan oleh beberapa paket modern
        # texlive-lang-indonesian: untuk dukungan bahasa Indonesia (opsional)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-pictures texlive-luatex texlive-lang-indonesian

      - name: Install Python dependencies
        run: |
          pip install PyGithub jinja2

      - name: Run bot script to generate question paper (PDF)
        # Mengirim input dari workflow ke skrip Python sebagai environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token rahasia GitHub, otomatis disediakan oleh Actions
          GITHUB_REPOSITORY: ${{ github.repository }} # Nama repositori (owner/repo_name)
          INPUT_SUBJECT: ${{ github.event.inputs.subject }}
          INPUT_GRADE: ${{ github.event.inputs.grade }}
          INPUT_EXAM_TITLE: ${{ github.event.inputs.exam_title }}
          INPUT_TEACHER_NAME: ${{ github.event.inputs.teacher_name }}
          INPUT_TOPIC_1: ${{ github.event.inputs.topic_1 }}
          INPUT_TOPIC_2: ${{ github.event.inputs.topic_2 }}
          INPUT_TOPIC_3: ${{ github.event.inputs.topic_3 }}
        run: python bot_scripts/generate_question.py